name: Zip and Upload

on: [push]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install demjson
        run: |
          pip install demjson
      - name: Run zipmcproject.py
        run: |
          python zipmcproject.py
      - name: Upload zip file
        uses: actions/upload-artifact@v2
        with:
          name: project-zip
          path: project.zip
