name: Zip and Upload

on:
  push:
    branches:
      - main
      - dev_progress
  workflow_dispatch:

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python version
        run: |
          python --version
      - name: Downgrade setuptools
        run: |
          pip install "setuptools<58.0.0"
      - name: Install demjson
        run: |
          pip install demjson
      - name: Run zipmcproject.py
        run: |
          python zipmcproject.py
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: "MintUI_Project_${{ github.sha }}"
          path: "*.mcpack"
          if-no-files-found: error
      - name: Cleanup Workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 10
